name = "hugo-theme-developer-portfolio"
license = "MIT"
licenselink = "https://github.com/jasonraimondi/hugo-theme-developer-portfolio/blob/master/LICENSE"
description = "A developer portfolio theme"
homepage = "https://hugo-theme-developer-portfolio.netlify.app"
tags = ["developer","blog"]
features = ["nightmode"]
min_version = "0.64"

[author]
  name = "Jason Raimondi"
  homepage = "https://jasonraimondi.com/"
