name = "developer-theme"
license = "MIT"
licenselink = "https://github.com/jasonraimondi/hugo-theme-developer-portfolio/blob/master/LICENSE"
description = ""
homepage = "https://jasonraimondi.com"
tags = ["blog"]
features = []
min_version = "0.54"

[author]
  name = "Jason Raimondi"
  homepage = "https://jasonraimondi.com/"
